BEGIN;

-- 评分周期与音符币学期分开记录。评分只读取当前周期内的数据：
-- 1) 最近一次手动开启新学期；
-- 2) 学生连续 28 天没有有效工作日练琴后，首次复练。
CREATE TABLE IF NOT EXISTS public.score_semesters (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL UNIQUE,
  source     TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.score_semesters
  ADD COLUMN IF NOT EXISTS week_target_snapshot JSONB;

ALTER TABLE public.score_semesters ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.score_semesters FROM anon, authenticated;

INSERT INTO public.score_semesters (started_at, source)
SELECT DISTINCT ct.created_at, 'coin_transaction_backfill'
FROM public.coin_transactions ct
WHERE ct.transaction_type = 'semester_reset'
  AND ct.created_at IS NOT NULL
ON CONFLICT (started_at) DO NOTHING;

-- 首次部署时，先使用当前线上目标算法保存老生目标，再替换成带
-- 学期边界的新算法，避免边界建立后丢失原目标。
DO $target_snapshot_backfill$
DECLARE
  semester_row RECORD;
  student_row RECORD;
  target_row RECORD;
  v_targets JSONB;
BEGIN
  FOR semester_row IN
    SELECT ss.id, ss.started_at
    FROM public.score_semesters ss
    WHERE ss.week_target_snapshot IS NULL
    ORDER BY ss.started_at
  LOOP
    v_targets := '{}'::JSONB;

    FOR student_row IN
      SELECT sb.student_name
      FROM public.student_baseline sb
      WHERE COALESCE(sb.mean_duration, 0) > 0
        AND EXISTS (
          SELECT 1
          FROM public.practice_sessions ps
          WHERE ps.student_name = sb.student_name
            AND ps.cleaned_duration > 0
            AND ps.session_start < semester_row.started_at
            AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
        )
    LOOP
      SELECT *
      INTO target_row
      FROM public.get_rule_v2_week_target_context(
        student_row.student_name,
        (DATE_TRUNC('week', semester_row.started_at AT TIME ZONE 'Asia/Shanghai') + INTERVAL '7 days')::DATE
      );

      IF target_row.final_target_week IS NOT NULL THEN
        v_targets := v_targets || jsonb_build_object(
          student_row.student_name,
          target_row.final_target_week
        );
      END IF;
    END LOOP;

    UPDATE public.score_semesters
    SET week_target_snapshot = NULLIF(v_targets, '{}'::JSONB)
    WHERE id = semester_row.id;
  END LOOP;
END;
$target_snapshot_backfill$;

CREATE OR REPLACE FUNCTION public.get_score_semester_start(
  p_cutoff TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TIMESTAMPTZ
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
  SELECT MAX(ss.started_at)
  FROM public.score_semesters ss
  WHERE ss.started_at < p_cutoff;
$function$;

CREATE OR REPLACE FUNCTION public.get_student_score_period_start_at(
  p_student_name TEXT,
  p_cutoff       TIMESTAMPTZ
)
RETURNS TIMESTAMPTZ
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH valid_sessions AS (
  SELECT
    ps.session_start,
    LAG(ps.session_start) OVER (ORDER BY ps.session_start) AS previous_session_start
  FROM public.practice_sessions ps
  WHERE ps.student_name = p_student_name
    AND ps.cleaned_duration > 0
    AND ps.session_start < p_cutoff
    AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
),
restart_points AS (
  SELECT vs.session_start
  FROM valid_sessions vs
  WHERE vs.previous_session_start IS NULL
     OR vs.session_start - vs.previous_session_start >= INTERVAL '28 days'
),
boundaries AS (
  SELECT public.get_score_semester_start(p_cutoff) AS semester_start,
         (SELECT MAX(rp.session_start) FROM restart_points rp) AS restart_start
)
SELECT NULLIF(
  GREATEST(
    COALESCE(b.semester_start, '-infinity'::TIMESTAMPTZ),
    COALESCE(b.restart_start, '-infinity'::TIMESTAMPTZ)
  ),
  '-infinity'::TIMESTAMPTZ
)
FROM boundaries b;
$function$;

CREATE OR REPLACE FUNCTION public.get_student_score_period_start(
  p_student_name  TEXT,
  p_snapshot_date DATE
)
RETURNS TIMESTAMPTZ
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH bounds AS (
  SELECT
    DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE AS current_monday,
    ((p_snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai') AS week_start,
    (((p_snapshot_date + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai') AS week_end
),
cutoff AS (
  SELECT CASE
    WHEN p_snapshot_date < b.current_monday THEN b.week_end
    WHEN p_snapshot_date = b.current_monday THEN LEAST(NOW(), b.week_end)
    ELSE b.week_start
  END AS cutoff_at
  FROM bounds b
)
SELECT public.get_student_score_period_start_at(p_student_name, c.cutoff_at)
FROM cutoff c;
$function$;

REVOKE ALL ON FUNCTION public.get_score_semester_start(TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_student_score_period_start_at(TEXT, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_student_score_period_start(TEXT, DATE) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_rule_v2_week_target_context(
  p_student_name TEXT,
  p_week_monday  DATE DEFAULT DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE
)
RETURNS TABLE (
  final_target_week    FLOAT8,
  personal_target_week FLOAT8,
  major_floor_week     FLOAT8,
  personal_week_ref    FLOAT8,
  peer_week_ref        FLOAT8,
  effective_mean       FLOAT8
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_major            TEXT;
  v_week_start_bjt   TIMESTAMPTZ;
  v_target_cutoff    TIMESTAMPTZ;
  v_period_start     TIMESTAMPTZ;
  v_semester_start   TIMESTAMPTZ;
  v_student_target   FLOAT8;
  v_peer_target      FLOAT8;
  v_period_mean      FLOAT8;
  v_period_count     INTEGER := 0;
  v_period_week_count INTEGER := 0;
  v_median_mean      FLOAT8;
  v_self_p50         FLOAT8;
  v_self_p70         FLOAT8;
  v_self_avg         FLOAT8;
  v_personal_ref     FLOAT8;
  v_peer_ref         FLOAT8;
  v_shrink_alpha     FLOAT8;
  v_effective_mean   FLOAT8;
  v_personal_target  FLOAT8;
  v_major_floor      FLOAT8;
  v_final_target     FLOAT8;
BEGIN
  SELECT sb.student_major
  INTO v_major
  FROM public.student_baseline sb
  WHERE sb.student_name = p_student_name;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_week_start_bjt := (p_week_monday::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai';
  v_target_cutoff := CASE
    WHEN p_week_monday = DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE
      THEN NOW()
    ELSE v_week_start_bjt + INTERVAL '7 days'
  END;
  v_semester_start := public.get_score_semester_start(v_target_cutoff);
  v_period_start := COALESCE(
    public.get_student_score_period_start(p_student_name, p_week_monday),
    v_week_start_bjt - INTERVAL '16 weeks'
  );

  IF v_semester_start IS NOT NULL THEN
    SELECT NULLIF((ss.week_target_snapshot ->> p_student_name), '')::FLOAT8
    INTO v_student_target
    FROM public.score_semesters ss
    WHERE ss.started_at = v_semester_start;

    IF v_student_target IS NULL THEN
      -- 新生首个有效周使用同教研室老生的平均周目标。
      SELECT AVG((ss.week_target_snapshot ->> sb.student_name)::FLOAT8)
      INTO v_peer_target
      FROM public.score_semesters ss
      JOIN public.student_baseline sb
        ON ss.week_target_snapshot ? sb.student_name
      WHERE ss.started_at = v_semester_start
        AND sb.student_major = v_major
        AND NULLIF(ss.week_target_snapshot ->> sb.student_name, '') IS NOT NULL;
    END IF;
  END IF;

  WITH recent_valid AS (
    SELECT ps.cleaned_duration
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= v_period_start
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    ORDER BY ps.session_start DESC
    LIMIT 30
  )
  SELECT AVG(rv.cleaned_duration)::FLOAT8, COUNT(*)::INTEGER
  INTO v_period_mean, v_period_count
  FROM recent_valid rv;

  SELECT COUNT(DISTINCT DATE_TRUNC(
    'week',
    ps.session_start AT TIME ZONE 'Asia/Shanghai'
  )::DATE)::INTEGER
  INTO v_period_week_count
  FROM public.practice_sessions ps
  WHERE ps.student_name = p_student_name
    AND ps.cleaned_duration > 0
    AND ps.session_start >= v_period_start
    AND ps.session_start < v_week_start_bjt
    AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6);

  WITH peer_ranked AS (
    SELECT
      ps.student_name,
      ps.cleaned_duration,
      ROW_NUMBER() OVER (PARTITION BY ps.student_name ORDER BY ps.session_start DESC) AS rn
    FROM public.practice_sessions ps
    JOIN public.student_baseline sb ON sb.student_name = ps.student_name
    WHERE ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '16 weeks')
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      AND (
        (v_major IS NOT NULL AND sb.student_major = v_major)
        OR v_major IS NULL
      )
  ),
  peer_means AS (
    SELECT pr.student_name, AVG(pr.cleaned_duration)::FLOAT8 AS mean_duration
    FROM peer_ranked pr
    WHERE pr.rn <= 30
    GROUP BY pr.student_name
  )
  SELECT percentile_cont(0.50) WITHIN GROUP (ORDER BY pm.mean_duration)
  INTO v_median_mean
  FROM peer_means pm;

  v_shrink_alpha := LEAST(1.0, COALESCE(v_period_count, 0)::FLOAT8 / 15.0);
  v_effective_mean := v_shrink_alpha * COALESCE(v_period_mean, 0.0)
                    + (1.0 - v_shrink_alpha) * COALESCE(v_median_mean, 30.0);
  v_effective_mean := GREATEST(v_effective_mean, 15.0);

  WITH self_weekly AS (
    SELECT
      DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE AS week_start,
      SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '16 weeks')
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    GROUP BY DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
    HAVING SUM(ps.cleaned_duration) > 0
  ),
  self_recent AS (
    SELECT
      sw.weekly_mins,
      ROW_NUMBER() OVER (ORDER BY sw.week_start DESC) AS rn
    FROM self_weekly sw
  )
  SELECT
    percentile_cont(0.50) WITHIN GROUP (ORDER BY sr.weekly_mins),
    percentile_cont(0.70) WITHIN GROUP (ORDER BY sr.weekly_mins),
    AVG(sr.weekly_mins)
  INTO v_self_p50, v_self_p70, v_self_avg
  FROM self_recent sr
  WHERE sr.rn <= 8;

  v_personal_ref := GREATEST(
    COALESCE(0.50 * v_self_p50 + 0.30 * v_self_p70 + 0.20 * v_self_avg, 0.0),
    GREATEST(v_effective_mean, 30.0) * 5.0
  );

  WITH peer_weekly AS (
    SELECT SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
    FROM public.practice_sessions ps
    JOIN public.student_baseline sb ON sb.student_name = ps.student_name
    WHERE ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '16 weeks')
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      AND (
        (v_major IS NOT NULL AND sb.student_major = v_major)
        OR v_major IS NULL
      )
    GROUP BY ps.student_name,
             DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
    HAVING SUM(ps.cleaned_duration) > 0
  )
  SELECT percentile_cont(0.50) WITHIN GROUP (ORDER BY pw.weekly_mins)
  INTO v_peer_ref
  FROM peer_weekly pw;

  v_peer_ref := GREATEST(COALESCE(v_peer_ref, v_personal_ref, 300.0), 240.0);
  v_personal_target := LEAST(1500.0, GREATEST(270.0, COALESCE(v_personal_ref, 300.0)));
  v_major_floor := LEAST(1500.0, GREATEST(240.0, v_peer_ref * 0.80));
  v_final_target := GREATEST(v_personal_target, v_major_floor);

  -- 学期开始时保留已有老生目标；没有个人快照的新生使用同教研室老生
  -- 平均目标，找不到参考时沿用基础默认目标 270 分钟/周。
  IF v_student_target IS NOT NULL THEN
    v_personal_target := LEAST(1500.0, GREATEST(270.0, v_student_target));
    v_major_floor := v_personal_target;
    v_final_target := v_personal_target;
  ELSIF v_period_start < v_week_start_bjt
        AND DATE_TRUNC('week', v_period_start AT TIME ZONE 'Asia/Shanghai')::DATE < p_week_monday
        AND v_period_week_count >= 1
        AND v_period_count >= 3 THEN
    -- 新生完成首个活跃周后，从第二周开始转入个人目标；个人样本仍不足时，
    -- v_effective_mean 会继续参考同专业样本收缩，避免少量记录把目标拉偏。
    v_personal_target := LEAST(1500.0, GREATEST(270.0, COALESCE(v_personal_ref, 300.0)));
    v_major_floor := v_personal_target;
    v_final_target := v_personal_target;
  ELSIF v_peer_target IS NOT NULL THEN
    v_personal_target := LEAST(1500.0, GREATEST(270.0, v_peer_target));
    v_major_floor := v_personal_target;
    v_final_target := v_personal_target;
  END IF;

  RETURN QUERY
  SELECT
    v_final_target,
    v_personal_target,
    v_major_floor,
    v_personal_ref,
    v_peer_ref,
    v_effective_mean;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_rule_v2_week_target_context(TEXT, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_rule_v2_week_target_context(TEXT, DATE) TO anon, authenticated;

-- 在开启新学期前保存老生当前目标。该快照只保存“目标”，不保存 W 的当周累计，
-- 因此新学期进度可以归零，而目标口径保持稳定。
CREATE OR REPLACE FUNCTION public.capture_score_semester_targets(
  p_semester_started_at TIMESTAMPTZ
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  student_row RECORD;
  target_row  RECORD;
  v_targets   JSONB := '{}'::JSONB;
  v_week      DATE;
BEGIN
  v_week := DATE_TRUNC('week', p_semester_started_at AT TIME ZONE 'Asia/Shanghai')::DATE;

  FOR student_row IN
    SELECT sb.student_name
    FROM public.student_baseline sb
    WHERE EXISTS (
      SELECT 1
      FROM public.practice_sessions ps
      WHERE ps.student_name = sb.student_name
        AND ps.cleaned_duration > 0
        AND ps.session_start < p_semester_started_at
        AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    )
    ORDER BY sb.student_name
  LOOP
    SELECT *
    INTO target_row
    FROM public.get_rule_v2_week_target_context(student_row.student_name, v_week);

    IF target_row.final_target_week IS NOT NULL
       AND target_row.final_target_week > 0 THEN
      v_targets := v_targets || jsonb_build_object(
        student_row.student_name,
        LEAST(1500.0, GREATEST(270.0, target_row.final_target_week))
      );
    END IF;
  END LOOP;

  RETURN NULLIF(v_targets, '{}'::JSONB);
END;
$function$;

REVOKE ALL ON FUNCTION public.capture_score_semester_targets(TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.compute_student_score_rule_v2_core(
  p_student_name  TEXT,
  p_snapshot_date DATE
)
RETURNS TABLE (
  composite_score  NUMERIC,
  raw_score        FLOAT8,
  baseline_score   FLOAT8,
  trend_score      FLOAT8,
  momentum_score   FLOAT8,
  accum_score      FLOAT8,
  w_score          FLOAT8,
  score_confidence FLOAT8,
  growth_velocity  FLOAT8,
  weeks_improving  INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  student_row             RECORD;
  target_context          RECORD;
  v_week_monday           DATE;
  v_current_monday        DATE;
  v_week_start_bjt        TIMESTAMPTZ;
  v_week_next_bjt         TIMESTAMPTZ;
  v_score_cutoff          TIMESTAMPTZ;
  v_period_start          TIMESTAMPTZ;
  v_period_week_monday    DATE;
  v_period_mean           FLOAT8 := 0.0;
  v_period_count          INTEGER := 0;
  v_period_outlier_rate   FLOAT8 := 0.0;
  v_period_short_rate     FLOAT8 := 0.0;
  v_hist_count            INTEGER := 0;
  v_b_score               FLOAT8 := 0.5;
  v_t_score               FLOAT8 := 0.5;
  v_m_score               FLOAT8 := 0.5;
  v_a_score               FLOAT8 := 0.5;
  v_w_score               FLOAT8 := 0.5;
  v_score_conf            FLOAT8 := 0.5;
  v_growth_velocity       FLOAT8 := 0.0;
  v_weeks_met             INTEGER := 0;
  v_outlier_penalty       FLOAT8 := 1.0;
  v_weight_b              FLOAT8;
  v_weight_t              FLOAT8;
  v_weight_m              FLOAT8;
  v_weight_a              FLOAT8;
  v_weight_w              FLOAT8;
  v_elapsed_days          INTEGER := 5;
  v_week_minutes          FLOAT8 := 0.0;
  v_week_completion       FLOAT8 := 0.0;
  v_target_week           FLOAT8 := 300.0;
  v_recent_avg            FLOAT8;
  v_older_avg             FLOAT8;
  v_recent_completion     FLOAT8;
  v_older_completion      FLOAT8;
  v_b_change              FLOAT8 := 0.5;
  v_t_change              FLOAT8 := 0.5;
  v_b_level               FLOAT8 := 0.5;
  v_t_level               FLOAT8 := 0.5;
  v_b_delta               FLOAT8 := 0.0;
  v_t_delta               FLOAT8 := 0.0;
  v_w1_mins               FLOAT8;
  v_w2_mins               FLOAT8;
  v_comp1                 FLOAT8;
  v_comp2                 FLOAT8;
  v_long_median           FLOAT8;
  v_long_active_ratio     FLOAT8 := 0.5;
  v_long_quality          FLOAT8 := 0.5;
  v_peer_level            FLOAT8 := 0.5;
  v_completion_sd         FLOAT8 := 0.0;
  v_weighted_completion   FLOAT8 := 0.0;
  velocity_row            RECORD;
  v_vel_count_4           INTEGER := 0;
  v_vel_sum_4             FLOAT8 := 0.0;
  v_vel_count_8           INTEGER := 0;
  v_vel_sum_8             FLOAT8 := 0.0;
BEGIN
  v_week_monday := p_snapshot_date;
  v_current_monday := DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;
  v_week_start_bjt := (v_week_monday::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai';
  v_week_next_bjt := v_week_start_bjt + INTERVAL '7 days';
  v_score_cutoff := CASE
    WHEN v_week_monday = v_current_monday THEN LEAST(NOW(), v_week_next_bjt)
    ELSE v_week_next_bjt
  END;

  SELECT *
  INTO student_row
  FROM public.student_baseline sb
  WHERE sb.student_name = p_student_name;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  v_period_start := COALESCE(
    public.get_student_score_period_start(p_student_name, p_snapshot_date),
    v_week_start_bjt
  );
  v_period_week_monday := DATE_TRUNC(
    'week',
    v_period_start AT TIME ZONE 'Asia/Shanghai'
  )::DATE;

  WITH recent_period_sessions AS (
    SELECT ps.cleaned_duration, ps.is_outlier
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.session_start >= v_period_start
      AND ps.session_start < v_score_cutoff
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    ORDER BY ps.session_start DESC
    LIMIT 30
  )
  SELECT
    COALESCE(AVG(rps.cleaned_duration) FILTER (WHERE rps.cleaned_duration > 0), 0.0)::FLOAT8,
    COUNT(*) FILTER (WHERE rps.cleaned_duration > 0)::INTEGER,
    COALESCE(AVG(CASE WHEN rps.is_outlier THEN 1.0 ELSE 0.0 END), 0.0)::FLOAT8,
    COALESCE(AVG(CASE
      WHEN rps.cleaned_duration >= 5 AND rps.cleaned_duration < 30 THEN 1.0
      ELSE 0.0
    END), 0.0)::FLOAT8
  INTO
    v_period_mean,
    v_period_count,
    v_period_outlier_rate,
    v_period_short_rate
  FROM recent_period_sessions rps;

  SELECT *
  INTO target_context
  FROM public.get_rule_v2_week_target_context(p_student_name, p_snapshot_date);

  v_target_week := COALESCE(target_context.final_target_week, 300.0);

  SELECT COUNT(*)
  INTO v_hist_count
  FROM public.student_score_history sh
  WHERE sh.student_name = p_student_name
    AND sh.composite_score > 0
    AND sh.snapshot_date >= v_period_week_monday
    AND sh.snapshot_date < v_week_monday
    AND EXISTS (
      SELECT 1
      FROM public.practice_sessions active_session
      WHERE active_session.student_name = sh.student_name
        AND active_session.cleaned_duration > 0
        AND active_session.session_start >= GREATEST(
          v_period_start,
          (sh.snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai'
        )
        AND active_session.session_start < (((sh.snapshot_date + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
        AND EXTRACT(DOW FROM active_session.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    );

  WITH recent_active AS (
    SELECT
      weekly.week_start,
      weekly.weekly_mins,
      ROW_NUMBER() OVER (ORDER BY weekly.week_start DESC) AS rn
    FROM (
      SELECT
        DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE AS week_start,
        SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
      FROM public.practice_sessions ps
      WHERE ps.student_name = p_student_name
        AND ps.cleaned_duration > 0
        AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '20 weeks')
        AND ps.session_start < v_week_start_bjt
        AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      GROUP BY DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
      HAVING SUM(ps.cleaned_duration) > 0
    ) weekly
  )
  SELECT
    MAX(CASE WHEN ra.rn = 1 THEN ra.weekly_mins END),
    MAX(CASE WHEN ra.rn = 2 THEN ra.weekly_mins END),
    AVG(CASE WHEN ra.rn <= 2 THEN ra.weekly_mins END),
    AVG(CASE WHEN ra.rn > 2 AND ra.rn <= 4 THEN ra.weekly_mins END)
  INTO v_w1_mins, v_w2_mins, v_recent_avg, v_older_avg
  FROM recent_active ra
  WHERE ra.rn <= 4;

  v_comp1 := LEAST(1.10, COALESCE(v_w1_mins, 0.0) / NULLIF(v_target_week, 0.0));
  v_comp2 := LEAST(1.10, COALESCE(v_w2_mins, 0.0) / NULLIF(v_target_week, 0.0));
  v_b_delta := COALESCE(v_comp1, 0.0) - COALESCE(v_comp2, 0.0);

  IF COALESCE(v_w1_mins, 0.0) > 0 THEN
    IF COALESCE(v_w2_mins, 0.0) > 0 THEN
      IF v_comp1 >= 0.92 AND v_comp2 >= 0.92 THEN
        v_b_change := GREATEST(0.68, LEAST(0.82, 0.72 + v_b_delta * 0.60));
      ELSIF ABS(v_b_delta) <= 0.06 THEN
        v_b_change := 0.5;
      ELSE
        v_b_change := 1.0 / (1.0 + EXP(-8.0 * v_b_delta));
      END IF;
    ELSE
      v_b_change := CASE
        WHEN v_comp1 >= 0.92 THEN 0.70
        WHEN v_comp1 >= 0.75 THEN 0.60
        WHEN v_comp1 >= 0.50 THEN 0.50
        ELSE 0.35
      END;
    END IF;

    v_b_level := CASE
      WHEN v_comp1 >= 1.00 THEN 0.85
      WHEN v_comp1 >= 0.92 THEN 0.75
      WHEN v_comp1 >= 0.75 THEN 0.62
      WHEN v_comp1 >= 0.50 THEN 0.48
      ELSE 0.32
    END;
    v_b_score := 0.70 * v_b_change + 0.30 * v_b_level;
  END IF;

  v_recent_completion := LEAST(1.10, COALESCE(v_recent_avg, 0.0) / NULLIF(v_target_week, 0.0));
  v_older_completion := LEAST(1.10, COALESCE(v_older_avg, 0.0) / NULLIF(v_target_week, 0.0));
  v_t_delta := COALESCE(v_recent_completion, 0.0) - COALESCE(v_older_completion, 0.0);

  IF v_recent_avg IS NOT NULL THEN
    IF v_older_avg IS NOT NULL THEN
      IF v_recent_completion BETWEEN 0.92 AND 1.08
         AND v_older_completion BETWEEN 0.92 AND 1.08 THEN
        v_t_change := GREATEST(0.68, LEAST(0.82, 0.72 + v_t_delta * 0.50));
      ELSIF ABS(v_t_delta) <= 0.06 THEN
        v_t_change := 0.5;
      ELSE
        v_t_change := 1.0 / (1.0 + EXP(-8.0 * v_t_delta));
      END IF;
    ELSE
      v_t_change := 0.5;
    END IF;

    v_t_level := CASE
      WHEN v_recent_completion >= 1.00 THEN 0.82
      WHEN v_recent_completion >= 0.92 THEN 0.74
      WHEN v_recent_completion >= 0.75 THEN 0.62
      WHEN v_recent_completion >= 0.50 THEN 0.48
      ELSE 0.34
    END;
    v_t_score := 0.65 * v_t_change + 0.35 * v_t_level;
  END IF;

  WITH momentum_weeks AS (
    SELECT
      weekly.week_start,
      LEAST(1.10, weekly.weekly_mins / NULLIF(v_target_week, 0.0)) AS completion,
      ROW_NUMBER() OVER (ORDER BY weekly.week_start DESC) AS rn
    FROM (
      SELECT
        DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE AS week_start,
        SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
      FROM public.practice_sessions ps
      WHERE ps.student_name = p_student_name
        AND ps.cleaned_duration > 0
        AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '12 weeks')
        AND ps.session_start < v_week_start_bjt
        AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      GROUP BY DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
      HAVING SUM(ps.cleaned_duration) > 0
    ) weekly
  ),
  momentum_recent AS (
    SELECT
      mw.rn,
      mw.completion,
      CASE mw.rn
        WHEN 1 THEN 0.35
        WHEN 2 THEN 0.30
        WHEN 3 THEN 0.20
        WHEN 4 THEN 0.15
        ELSE 0.0
      END AS weight
    FROM momentum_weeks mw
    WHERE mw.rn <= 4
  )
  SELECT
    COALESCE(SUM(mr.weight * LEAST(1.0, mr.completion)), 0.0),
    COALESCE(STDDEV_POP(mr.completion), 0.0),
    COALESCE(COUNT(*) FILTER (WHERE mr.completion >= 0.92), 0)
  INTO v_weighted_completion, v_completion_sd, v_weeks_met
  FROM momentum_recent mr;

  IF v_hist_count < 2 THEN
    v_m_score := 0.5;
  ELSE
    v_m_score := GREATEST(0.0, LEAST(1.0,
      0.78 * v_weighted_completion
      + 0.22 * GREATEST(0.0, LEAST(1.0, 1.0 - COALESCE(v_completion_sd, 0.0) / 0.35))
    ));
  END IF;

  WITH self_long AS (
    SELECT
      DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE AS week_start,
      SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '20 weeks')
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    GROUP BY DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
    HAVING SUM(ps.cleaned_duration) > 0
  ),
  self_long_recent AS (
    SELECT
      sl.weekly_mins,
      ROW_NUMBER() OVER (ORDER BY sl.week_start DESC) AS rn
    FROM self_long sl
  )
  SELECT
    percentile_cont(0.50) WITHIN GROUP (ORDER BY slr.weekly_mins),
    LEAST(1.0, COUNT(*)::FLOAT8 / 8.0)
  INTO v_long_median, v_long_active_ratio
  FROM self_long_recent slr
  WHERE slr.rn <= 12;

  v_long_median := COALESCE(v_long_median, v_target_week * 0.70);

  WITH peer_long AS (
    SELECT SUM(ps.cleaned_duration)::FLOAT8 AS weekly_mins
    FROM public.practice_sessions ps
    JOIN public.student_baseline sb ON sb.student_name = ps.student_name
    WHERE ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_period_start, v_week_start_bjt - INTERVAL '20 weeks')
      AND ps.session_start < v_week_start_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      AND (
        (student_row.student_major IS NOT NULL AND sb.student_major = student_row.student_major)
        OR student_row.student_major IS NULL
      )
    GROUP BY ps.student_name,
             DATE_TRUNC('week', ps.session_start AT TIME ZONE 'Asia/Shanghai')::DATE
    HAVING SUM(ps.cleaned_duration) > 0
  )
  SELECT COALESCE(AVG(CASE WHEN pl.weekly_mins <= v_long_median THEN 1.0 ELSE 0.0 END), 0.5)
  INTO v_peer_level
  FROM peer_long pl;

  v_long_quality := GREATEST(
    0.0,
    LEAST(
      1.0,
      v_long_active_ratio
      * (1.0 - 0.50 * v_period_outlier_rate)
      * (1.0 - 0.30 * v_period_short_rate)
    )
  );
  v_a_score := GREATEST(0.0, LEAST(1.0, 0.75 * v_peer_level + 0.25 * v_long_quality));

  SELECT COALESCE(SUM(ps.cleaned_duration), 0.0)
  INTO v_week_minutes
  FROM public.practice_sessions ps
  WHERE ps.student_name = p_student_name
    AND ps.cleaned_duration > 0
    AND ps.session_start >= GREATEST(v_week_start_bjt, v_period_start)
    AND ps.session_start < v_score_cutoff
    AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6);

  IF v_week_monday = v_current_monday THEN
    v_elapsed_days := CASE EXTRACT(DOW FROM NOW() AT TIME ZONE 'Asia/Shanghai')::INTEGER
      WHEN 0 THEN 5
      WHEN 6 THEN 5
      ELSE EXTRACT(DOW FROM NOW() AT TIME ZONE 'Asia/Shanghai')::INTEGER
    END;
  ELSE
    v_elapsed_days := 5;
  END IF;

  IF v_elapsed_days > 0 THEN
    v_week_completion := v_week_minutes
      / NULLIF(v_target_week * (v_elapsed_days::FLOAT8 / 5.0), 0.0);
  ELSE
    v_week_completion := 0.0;
  END IF;

  v_w_score := CASE
    WHEN v_week_completion <= 0.0 THEN 0.0
    WHEN v_week_completion < 0.50 THEN 0.20 + 0.50 * (v_week_completion / 0.50)
    WHEN v_week_completion < 1.00 THEN 0.70 + 0.20 * ((v_week_completion - 0.50) / 0.50)
    WHEN v_week_completion < 1.10 THEN 0.90 + 0.05 * ((v_week_completion - 1.00) / 0.10)
    ELSE 0.95
  END;
  v_w_score := GREATEST(0.0, LEAST(0.95, v_w_score));

  IF v_hist_count < 4 THEN
    v_weight_b := 0.08;
    v_weight_t := 0.05;
    v_weight_m := 0.15;
    v_weight_a := 0.30;
    v_weight_w := 0.42;
  ELSIF v_hist_count < 12 THEN
    v_weight_b := 0.12;
    v_weight_t := 0.10;
    v_weight_m := 0.20;
    v_weight_a := 0.30;
    v_weight_w := 0.28;
  ELSE
    v_weight_b := 0.12;
    v_weight_t := 0.12;
    v_weight_m := 0.24;
    v_weight_a := 0.30;
    v_weight_w := 0.22;
  END IF;

  v_outlier_penalty := CASE
    WHEN v_period_outlier_rate <= 0.25
      THEN 1.0 - 0.6 * v_period_outlier_rate
    WHEN v_period_outlier_rate <= 0.60
      THEN 0.85 - 1.0 * (v_period_outlier_rate - 0.25)
    ELSE 0.50 * EXP(-3.0 * (v_period_outlier_rate - 0.60))
  END;

  composite_score := ROUND((
    GREATEST(0.0, LEAST(1.0,
      v_weight_b * v_b_score
      + v_weight_t * v_t_score
      + v_weight_m * v_m_score
      + v_weight_a * v_a_score
      + v_weight_w * v_w_score
    )) * v_outlier_penalty
  )::NUMERIC * 100.0, 1);

  raw_score := composite_score / 100.0;
  baseline_score := v_b_score;
  trend_score := v_t_score;
  momentum_score := v_m_score;
  accum_score := v_a_score;
  w_score := v_w_score;

  v_score_conf := GREATEST(0.0, LEAST(1.0,
    LEAST(1.0, v_hist_count::FLOAT8 / 12.0) * 0.55
    + (1.0 - v_period_outlier_rate) * 0.20
    + (1.0 - v_period_short_rate) * 0.10
    + CASE WHEN v_week_monday = v_current_monday THEN 0.15 ELSE 0.10 END
  ));
  score_confidence := v_score_conf;

  FOR velocity_row IN
    SELECT sh.composite_score::FLOAT8 AS score
    FROM public.student_score_history sh
    WHERE sh.student_name = p_student_name
      AND sh.composite_score > 0
      AND sh.snapshot_date >= v_period_week_monday
      AND sh.snapshot_date < v_week_monday
      AND EXISTS (
        SELECT 1
        FROM public.practice_sessions active_session
        WHERE active_session.student_name = sh.student_name
          AND active_session.cleaned_duration > 0
          AND active_session.session_start >= GREATEST(
            v_period_start,
            (sh.snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai'
          )
          AND active_session.session_start < (((sh.snapshot_date + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
          AND EXTRACT(DOW FROM active_session.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
      )
    ORDER BY sh.snapshot_date DESC
    LIMIT 8
  LOOP
    v_vel_count_8 := v_vel_count_8 + 1;
    v_vel_sum_8 := v_vel_sum_8 + velocity_row.score;
    IF v_vel_count_8 <= 4 THEN
      v_vel_count_4 := v_vel_count_4 + 1;
      v_vel_sum_4 := v_vel_sum_4 + velocity_row.score;
    END IF;
  END LOOP;

  IF v_vel_count_4 > 0 AND v_vel_count_8 > 4 THEN
    v_growth_velocity := (
      v_vel_sum_4 / v_vel_count_4
      - (v_vel_sum_8 - v_vel_sum_4) / NULLIF(v_vel_count_8 - v_vel_count_4, 0)
    ) / 100.0;
  END IF;

  growth_velocity := COALESCE(v_growth_velocity, 0.0);
  weeks_improving := COALESCE(v_weeks_met, 0);
  RETURN NEXT;
END;
$function$;

REVOKE ALL ON FUNCTION public.compute_student_score_rule_v2_core(TEXT, DATE) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_student_score_period_metrics(
  p_student_name  TEXT,
  p_snapshot_date DATE
)
RETURNS TABLE (
  period_start       TIMESTAMPTZ,
  mean_duration      FLOAT8,
  std_duration       FLOAT8,
  outlier_rate       FLOAT8,
  short_session_rate FLOAT8,
  record_count       INTEGER,
  alpha              FLOAT8,
  weekday_pattern    JSONB
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_current_monday DATE;
  v_week_start     TIMESTAMPTZ;
  v_week_end       TIMESTAMPTZ;
  v_cutoff         TIMESTAMPTZ;
  v_period_start   TIMESTAMPTZ;
  v_mean           FLOAT8 := 0.0;
  v_std            FLOAT8;
  v_outlier_rate   FLOAT8 := 0.0;
  v_short_rate     FLOAT8 := 0.0;
  v_count          INTEGER := 0;
  v_cv             FLOAT8 := 0.5;
  v_alpha          FLOAT8 := 0.82;
  v_lambda         FLOAT8 := 0.0;
  v_weekday        JSONB := '{}'::JSONB;
BEGIN
  v_current_monday := DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;
  v_week_start := (p_snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai';
  v_week_end := v_week_start + INTERVAL '7 days';
  v_cutoff := CASE
    WHEN p_snapshot_date < v_current_monday THEN v_week_end
    WHEN p_snapshot_date = v_current_monday THEN LEAST(NOW(), v_week_end)
    ELSE v_week_start
  END;
  v_period_start := COALESCE(
    public.get_student_score_period_start_at(p_student_name, v_cutoff),
    v_week_start
  );

  WITH recent AS (
    SELECT
      ps.cleaned_duration,
      ps.is_outlier,
      EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai')::INTEGER AS dow
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.session_start >= v_period_start
      AND ps.session_start < v_cutoff
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    ORDER BY ps.session_start DESC
    LIMIT 30
  )
  SELECT
    COALESCE(AVG(r.cleaned_duration) FILTER (WHERE r.cleaned_duration > 0), 0.0)::FLOAT8,
    STDDEV(r.cleaned_duration) FILTER (WHERE r.cleaned_duration > 0)::FLOAT8,
    COALESCE(AVG(CASE WHEN r.is_outlier THEN 1.0 ELSE 0.0 END), 0.0)::FLOAT8,
    COALESCE(AVG(CASE
      WHEN r.cleaned_duration >= 5 AND r.cleaned_duration < 30 THEN 1.0
      ELSE 0.0
    END), 0.0)::FLOAT8,
    COUNT(*) FILTER (WHERE r.cleaned_duration > 0)::INTEGER
  INTO v_mean, v_std, v_outlier_rate, v_short_rate, v_count
  FROM recent r;

  v_std := CASE
    WHEN v_count < 2 THEN NULL
    WHEN COALESCE(v_std, 0.0) < 1.0 THEN 1.0
    ELSE v_std
  END;
  v_cv := CASE
    WHEN v_mean > 0 AND v_std IS NOT NULL THEN v_std / v_mean
    ELSE 0.5
  END;
  v_alpha := 1.0
    - CASE WHEN v_mean > 0 THEN LEAST(0.15, 5.0 / v_mean) ELSE 0.15 END
    - LEAST(0.20, v_cv * 0.15)
    - CASE
        WHEN v_outlier_rate <= 0.30 THEN 0.08 * v_outlier_rate
        ELSE 0.024 + 0.40 * (v_outlier_rate - 0.30)
      END
    - 0.05 * v_short_rate;

  IF v_count < 10 THEN
    v_lambda := 1.0 - v_count::FLOAT8 / 10.0;
    v_alpha := v_lambda * 0.82 + (1.0 - v_lambda) * v_alpha;
  END IF;
  v_alpha := GREATEST(0.5, LEAST(1.0, v_alpha));

  WITH recent_valid AS (
    SELECT EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai')::INTEGER AS dow
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= v_period_start
      AND ps.session_start < v_cutoff
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    ORDER BY ps.session_start DESC
    LIMIT 30
  )
  SELECT COALESCE(jsonb_object_agg(counts.dow::TEXT, counts.cnt), '{}'::JSONB)
  INTO v_weekday
  FROM (
    SELECT rv.dow, COUNT(*) AS cnt
    FROM recent_valid rv
    GROUP BY rv.dow
  ) counts;

  RETURN QUERY
  SELECT
    v_period_start,
    v_mean,
    v_std,
    v_outlier_rate,
    v_short_rate,
    v_count,
    v_alpha,
    v_weekday;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_student_score_period_metrics(TEXT, DATE) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.compute_student_score(p_student_name TEXT)
RETURNS TABLE(composite_score NUMERIC, raw_score FLOAT8)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  calc             RECORD;
  metrics          RECORD;
  v_week_monday    DATE;
  v_week_start_bjt TIMESTAMPTZ;
  v_has_session    BOOLEAN;
BEGIN
  v_week_monday := DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;
  v_week_start_bjt := (v_week_monday::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai';

  IF NOT EXISTS (
    SELECT 1
    FROM public.student_baseline sb
    WHERE sb.student_name = p_student_name
  ) THEN
    RETURN;
  END IF;

  SELECT *
  INTO metrics
  FROM public.get_student_score_period_metrics(p_student_name, v_week_monday);

  SELECT EXISTS (
    SELECT 1
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_week_start_bjt, metrics.period_start)
      AND ps.session_start < LEAST(NOW(), v_week_start_bjt + INTERVAL '7 days')
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
  )
  INTO v_has_session;

  PERFORM set_config('app.computing_score', 'true', true);

  IF NOT v_has_session THEN
    INSERT INTO public.student_score_history (
      student_name,
      snapshot_date,
      composite_score,
      raw_score,
      baseline_score,
      trend_score,
      momentum_score,
      accum_score,
      outlier_rate,
      short_session_rate,
      mean_duration,
      record_count
    ) VALUES (
      p_student_name,
      v_week_monday,
      0,
      0.0,
      NULL,
      NULL,
      NULL,
      NULL,
      0.0,
      0.0,
      0.0,
      0
    )
    ON CONFLICT (student_name, snapshot_date) DO UPDATE SET
      composite_score = 0,
      raw_score = 0.0,
      baseline_score = NULL,
      trend_score = NULL,
      momentum_score = NULL,
      accum_score = NULL,
      outlier_rate = 0.0,
      short_session_rate = 0.0,
      mean_duration = 0.0,
      record_count = 0;

    UPDATE public.student_baseline sb
    SET
      composite_score = 0,
      raw_score = 0.0,
      baseline_score = NULL,
      trend_score = NULL,
      momentum_score = NULL,
      accum_score = NULL,
      w_score = 0.0,
      score_confidence = 0.0,
      growth_velocity = 0.0,
      weeks_improving = 0,
      last_updated = NOW()
    WHERE sb.student_name = p_student_name;

    PERFORM set_config('app.computing_score', 'false', true);
    RETURN QUERY SELECT 0::NUMERIC, 0.0::FLOAT8;
    RETURN;
  END IF;

  SELECT *
  INTO calc
  FROM public.compute_student_score_rule_v2_core(p_student_name, v_week_monday);

  IF NOT FOUND THEN
    PERFORM set_config('app.computing_score', 'false', true);
    RETURN;
  END IF;

  INSERT INTO public.student_score_history (
    student_name,
    snapshot_date,
    composite_score,
    raw_score,
    baseline_score,
    trend_score,
    momentum_score,
    accum_score,
    outlier_rate,
    short_session_rate,
    mean_duration,
    record_count
  ) VALUES (
    p_student_name,
    v_week_monday,
    calc.composite_score,
    calc.raw_score,
    calc.baseline_score,
    calc.trend_score,
    calc.momentum_score,
    calc.accum_score,
    metrics.outlier_rate,
    metrics.short_session_rate,
    metrics.mean_duration,
    metrics.record_count
  )
  ON CONFLICT (student_name, snapshot_date) DO UPDATE SET
    composite_score = EXCLUDED.composite_score,
    raw_score = EXCLUDED.raw_score,
    baseline_score = EXCLUDED.baseline_score,
    trend_score = EXCLUDED.trend_score,
    momentum_score = EXCLUDED.momentum_score,
    accum_score = EXCLUDED.accum_score,
    outlier_rate = EXCLUDED.outlier_rate,
    short_session_rate = EXCLUDED.short_session_rate,
    mean_duration = EXCLUDED.mean_duration,
    record_count = EXCLUDED.record_count;

  UPDATE public.student_baseline sb
  SET
    mean_duration = metrics.mean_duration,
    std_duration = metrics.std_duration,
    outlier_rate = metrics.outlier_rate,
    short_session_rate = metrics.short_session_rate,
    alpha = metrics.alpha,
    record_count = metrics.record_count,
    weekday_pattern = metrics.weekday_pattern,
    is_cold_start = metrics.record_count < 10,
    composite_score = calc.composite_score,
    raw_score = calc.raw_score,
    baseline_score = calc.baseline_score,
    trend_score = calc.trend_score,
    momentum_score = calc.momentum_score,
    accum_score = calc.accum_score,
    w_score = calc.w_score,
    w_score_updated_at = NOW(),
    score_confidence = calc.score_confidence,
    growth_velocity = calc.growth_velocity,
    weeks_improving = calc.weeks_improving,
    last_updated = NOW()
  WHERE sb.student_name = p_student_name;

  PERFORM set_config('app.computing_score', 'false', true);
  RETURN QUERY SELECT calc.composite_score, calc.raw_score;
END;
$function$;

CREATE OR REPLACE FUNCTION public.compute_student_score_as_of(
  p_student_name  TEXT,
  p_snapshot_date DATE
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  calc             RECORD;
  metrics          RECORD;
  v_week_start_bjt TIMESTAMPTZ;
  v_week_next_bjt  TIMESTAMPTZ;
  v_has_session    BOOLEAN;
BEGIN
  v_week_start_bjt := (p_snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai';
  v_week_next_bjt := v_week_start_bjt + INTERVAL '7 days';

  IF NOT EXISTS (
    SELECT 1
    FROM public.student_baseline sb
    WHERE sb.student_name = p_student_name
  ) THEN
    RETURN;
  END IF;

  SELECT *
  INTO metrics
  FROM public.get_student_score_period_metrics(p_student_name, p_snapshot_date);

  SELECT EXISTS (
    SELECT 1
    FROM public.practice_sessions ps
    WHERE ps.student_name = p_student_name
      AND ps.cleaned_duration > 0
      AND ps.session_start >= GREATEST(v_week_start_bjt, metrics.period_start)
      AND ps.session_start < v_week_next_bjt
      AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
  )
  INTO v_has_session;

  IF NOT v_has_session THEN
    INSERT INTO public.student_score_history (
      student_name,
      snapshot_date,
      composite_score,
      raw_score,
      baseline_score,
      trend_score,
      momentum_score,
      accum_score,
      outlier_rate,
      short_session_rate,
      mean_duration,
      record_count
    ) VALUES (
      p_student_name,
      p_snapshot_date,
      0,
      0.0,
      NULL,
      NULL,
      NULL,
      NULL,
      0.0,
      0.0,
      0.0,
      0
    )
    ON CONFLICT (student_name, snapshot_date) DO UPDATE SET
      composite_score = 0,
      raw_score = 0.0,
      baseline_score = NULL,
      trend_score = NULL,
      momentum_score = NULL,
      accum_score = NULL,
      outlier_rate = 0.0,
      short_session_rate = 0.0,
      mean_duration = 0.0,
      record_count = 0;
    RETURN;
  END IF;

  SELECT *
  INTO calc
  FROM public.compute_student_score_rule_v2_core(p_student_name, p_snapshot_date);

  IF NOT FOUND THEN
    RETURN;
  END IF;

  INSERT INTO public.student_score_history (
    student_name,
    snapshot_date,
    composite_score,
    raw_score,
    baseline_score,
    trend_score,
    momentum_score,
    accum_score,
    outlier_rate,
    short_session_rate,
    mean_duration,
    record_count
  ) VALUES (
    p_student_name,
    p_snapshot_date,
    calc.composite_score,
    calc.raw_score,
    calc.baseline_score,
    calc.trend_score,
    calc.momentum_score,
    calc.accum_score,
    metrics.outlier_rate,
    metrics.short_session_rate,
    metrics.mean_duration,
    metrics.record_count
  )
  ON CONFLICT (student_name, snapshot_date) DO UPDATE SET
    composite_score = EXCLUDED.composite_score,
    raw_score = EXCLUDED.raw_score,
    baseline_score = EXCLUDED.baseline_score,
    trend_score = EXCLUDED.trend_score,
    momentum_score = EXCLUDED.momentum_score,
    accum_score = EXCLUDED.accum_score,
    outlier_rate = EXCLUDED.outlier_rate,
    short_session_rate = EXCLUDED.short_session_rate,
    mean_duration = EXCLUDED.mean_duration,
    record_count = EXCLUDED.record_count;
END;
$function$;

REVOKE ALL ON FUNCTION public.compute_student_score(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.compute_student_score_as_of(TEXT, DATE) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_student_week_progress_context(
  p_student_name TEXT,
  p_week_monday  DATE DEFAULT NULL,
  p_as_of_date   DATE DEFAULT NULL
)
RETURNS TABLE (
  week_monday                  DATE,
  as_of_date                   DATE,
  is_workday                   BOOLEAN,
  elapsed_workdays             INTEGER,
  remaining_workdays           INTEGER,
  week_target_minutes          NUMERIC,
  settled_week_minutes         NUMERIC,
  settled_before_today_minutes NUMERIC,
  settled_today_minutes        NUMERIC,
  settled_session_count        INTEGER,
  expected_to_date_minutes     NUMERIC,
  today_target_minutes         NUMERIC,
  remaining_week_minutes       NUMERIC,
  shortfall_to_pace_minutes    NUMERIC,
  week_completion_ratio        NUMERIC,
  pace_completion_ratio        NUMERIC
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH params AS (
  SELECT COALESCE(p_as_of_date, (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE) AS reference_date
),
calendar AS (
  SELECT
    COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE) AS monday,
    p.reference_date,
    (
      p.reference_date >= COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE)
      AND p.reference_date < COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE) + 5
    ) AS workday,
    LEAST(
      5,
      GREATEST(
        0,
        p.reference_date - COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE) + 1
      )
    )::INTEGER AS elapsed_days,
    CASE
      WHEN p.reference_date >= COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE)
       AND p.reference_date < COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE) + 5
        THEN (
          5 - (
            p.reference_date
            - COALESCE(p_week_monday, DATE_TRUNC('week', p.reference_date::TIMESTAMP)::DATE)
          )
        )::INTEGER
      ELSE 0
    END AS remaining_days
  FROM params p
),
bounded AS (
  SELECT
    c.*,
    ((LEAST(c.monday + 7, c.reference_date + 1)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai') AS cutoff_at,
    public.get_student_score_period_start_at(
      p_student_name,
      ((LEAST(c.monday + 7, c.reference_date + 1)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
    ) AS period_start
  FROM calendar c
),
target AS (
  SELECT
    b.*,
    ctx.final_target_week::NUMERIC AS target_minutes
  FROM bounded b
  CROSS JOIN LATERAL public.get_rule_v2_week_target_context(p_student_name, b.monday) ctx
),
usage AS (
  SELECT
    t.monday,
    t.reference_date,
    t.workday,
    t.elapsed_days,
    t.remaining_days,
    t.target_minutes,
    COALESCE(SUM(ps.cleaned_duration), 0)::NUMERIC AS week_minutes,
    COALESCE(SUM(ps.cleaned_duration) FILTER (
      WHERE ps.session_start < ((t.reference_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
    ), 0)::NUMERIC AS before_today_minutes,
    COALESCE(SUM(ps.cleaned_duration) FILTER (
      WHERE ps.session_start >= ((t.reference_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
        AND ps.session_start < (((t.reference_date + 1)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
    ), 0)::NUMERIC AS today_minutes,
    COUNT(ps.*)::INTEGER AS session_count
  FROM target t
  LEFT JOIN public.practice_sessions ps
    ON ps.student_name = p_student_name
   AND ps.cleaned_duration > 0
   AND ps.session_start >= GREATEST(
     ((t.monday::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai'),
     COALESCE(t.period_start, ((t.monday::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai'))
   )
   AND ps.session_start < t.cutoff_at
   AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
  GROUP BY
    t.monday,
    t.reference_date,
    t.workday,
    t.elapsed_days,
    t.remaining_days,
    t.target_minutes
),
metrics AS (
  SELECT u.*, (u.target_minutes * u.elapsed_days / 5.0)::NUMERIC AS expected_minutes
  FROM usage u
)
SELECT
  m.monday,
  m.reference_date,
  m.workday,
  m.elapsed_days,
  m.remaining_days,
  ROUND(m.target_minutes, 2),
  ROUND(m.week_minutes, 2),
  ROUND(m.before_today_minutes, 2),
  ROUND(m.today_minutes, 2),
  m.session_count,
  ROUND(m.expected_minutes, 2),
  ROUND(CASE
    WHEN m.workday THEN GREATEST(m.expected_minutes - m.before_today_minutes, 0)
    ELSE 0
  END, 2),
  ROUND(GREATEST(m.target_minutes - m.week_minutes, 0), 2),
  ROUND(GREATEST(m.expected_minutes - m.week_minutes, 0), 2),
  ROUND((m.week_minutes / NULLIF(m.target_minutes, 0))::NUMERIC, 4),
  ROUND((m.week_minutes / NULLIF(m.expected_minutes, 0))::NUMERIC, 4)
FROM metrics m;
$function$;

REVOKE ALL ON FUNCTION public.get_student_week_progress_context(TEXT, DATE, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_student_week_progress_context(TEXT, DATE, DATE) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_weekly_decline_leaderboard(
  p_week_monday DATE DEFAULT DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE
)
RETURNS TABLE (
  board                  TEXT,
  rank_no                INTEGER,
  student_name           TEXT,
  student_major          TEXT,
  student_grade          TEXT,
  display_score          NUMERIC,
  alpha                  NUMERIC,
  trend_score            NUMERIC,
  mean_duration          NUMERIC,
  record_count           INTEGER,
  recent10_outlier_rate  NUMERIC,
  recent10_mean_dur      NUMERIC,
  recent10_count         INTEGER,
  target_minutes         NUMERIC,
  completed_minutes      NUMERIC,
  completion_ratio       NUMERIC,
  shortfall_minutes      NUMERIC,
  week_session_count     INTEGER
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH week_context AS (
  SELECT
    COALESCE(p_week_monday, DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE) AS monday,
    (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE AS today,
    CASE
      WHEN (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE < COALESCE(p_week_monday, DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE)
        THEN 0
      WHEN (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE >= COALESCE(p_week_monday, DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE) + 5
        THEN 5
      ELSE EXTRACT(DOW FROM (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE)::INTEGER
    END AS elapsed_workdays
),
current_students AS (
  SELECT DISTINCT ON (sd.name)
    sb.student_name,
    COALESCE(NULLIF(BTRIM(sd.major), ''), sb.student_major) AS student_major,
    COALESCE(NULLIF(BTRIM(sd.grade), ''), sb.student_grade) AS student_grade,
    sb.alpha,
    sb.mean_duration,
    sb.record_count
  FROM public.student_database sd
  JOIN public.student_baseline sb ON sb.student_name = sd.name
  WHERE COALESCE(sd.archived, FALSE) IS FALSE
    AND NULLIF(BTRIM(sd.name), '') IS NOT NULL
  ORDER BY sd.name, sd.updated_at DESC NULLS LAST, sd.id DESC
),
targeted_students AS (
  SELECT
    cs.*,
    wc.monday AS week_monday,
    metrics.period_start,
    metrics.record_count AS period_record_count,
    EXISTS (
      SELECT 1
      FROM public.score_semesters ss
      WHERE ss.started_at = public.get_score_semester_start(
        CASE
          WHEN wc.monday = DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE
            THEN NOW()
          ELSE (((wc.monday + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
        END
      )
        AND COALESCE(ss.week_target_snapshot, '{}'::JSONB) ? cs.student_name
    ) AS has_saved_target,
    progress.week_target_minutes AS target_minutes,
    progress.settled_week_minutes AS completed_minutes,
    progress.pace_completion_ratio AS completion_ratio,
    progress.expected_to_date_minutes AS expected_minutes,
    progress.shortfall_to_pace_minutes AS shortfall_minutes,
    progress.settled_session_count AS week_session_count,
    progress.elapsed_workdays
  FROM current_students cs
  CROSS JOIN week_context wc
  CROSS JOIN LATERAL public.get_student_score_period_metrics(cs.student_name, wc.monday) metrics
  CROSS JOIN LATERAL public.get_student_week_progress_context(
    cs.student_name,
    wc.monday,
    NULL
  ) progress
),
eligible AS (
  SELECT ts.*
  FROM targeted_students ts
  WHERE ts.week_session_count > 0
    AND ts.elapsed_workdays > 0
    -- 老生沿用已保存的周目标；新生首个活跃周不扣币，至少完成一个
    -- 完整周后且当前周有 3 次有效记录，才进入缩水榜。
    AND (
      ts.has_saved_target
      OR (
        DATE_TRUNC('week', ts.period_start AT TIME ZONE 'Asia/Shanghai')::DATE < ts.week_monday
        AND ts.week_session_count >= 3
      )
    )
),
ranked AS (
  SELECT
    ROW_NUMBER() OVER (
      ORDER BY completion_ratio ASC,
               shortfall_minutes DESC,
               completed_minutes ASC,
               student_name ASC
    )::INTEGER AS rank_no,
    e.*
  FROM eligible e
  WHERE e.completion_ratio < 0.70
)
SELECT
  '缩水榜'::TEXT,
  r.rank_no,
  r.student_name,
  r.student_major,
  r.student_grade,
  ROUND((r.completion_ratio * 100)::NUMERIC, 1),
  r.alpha,
  NULL::NUMERIC,
  r.mean_duration,
  r.period_record_count::INTEGER,
  NULL::NUMERIC,
  NULL::NUMERIC,
  NULL::INTEGER,
  ROUND(r.target_minutes, 2),
  ROUND(r.completed_minutes, 2),
  ROUND(r.completion_ratio, 4),
  ROUND(r.shortfall_minutes, 2),
  r.week_session_count
FROM ranked r
ORDER BY r.rank_no;
$function$;

REVOKE ALL ON FUNCTION public.get_weekly_decline_leaderboard(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_weekly_decline_leaderboard(DATE) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_weekly_leaderboards()
RETURNS TABLE (
  board                 TEXT,
  rank_no               INTEGER,
  student_name          TEXT,
  student_major         TEXT,
  student_grade         TEXT,
  display_score         NUMERIC,
  alpha                 NUMERIC,
  trend_score           NUMERIC,
  mean_duration         NUMERIC,
  record_count          INTEGER,
  recent10_outlier_rate NUMERIC,
  recent10_mean_dur     NUMERIC,
  recent10_count        INTEGER
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH week_context AS (
  SELECT
    DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE AS monday,
    ((DATE_TRUNC('week', NOW() AT TIME ZONE 'Asia/Shanghai')::DATE::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai') AS week_start,
    NOW() AS cutoff_at
),
current_students AS (
  SELECT DISTINCT ON (sd.name)
    sd.name AS student_name,
    COALESCE(NULLIF(BTRIM(sd.major), ''), sb.student_major) AS student_major,
    COALESCE(NULLIF(BTRIM(sd.grade), ''), sb.student_grade) AS student_grade
  FROM public.student_database sd
  JOIN public.student_baseline sb ON sb.student_name = sd.name
  WHERE COALESCE(sd.archived, FALSE) IS FALSE
    AND NULLIF(BTRIM(sd.name), '') IS NOT NULL
  ORDER BY sd.name, sd.updated_at DESC NULLS LAST, sd.id DESC
),
periods AS (
  SELECT
    cs.*,
    metrics.period_start,
    metrics.mean_duration,
    metrics.record_count,
    metrics.alpha
  FROM current_students cs
  CROSS JOIN week_context wc
  CROSS JOIN LATERAL public.get_student_score_period_metrics(cs.student_name, wc.monday) metrics
),
recent_ranked AS (
  SELECT
    p.student_name,
    ps.is_outlier,
    ps.cleaned_duration,
    ROW_NUMBER() OVER (PARTITION BY p.student_name ORDER BY ps.session_start DESC) AS rn
  FROM periods p
  CROSS JOIN week_context wc
  JOIN public.practice_sessions ps
    ON ps.student_name = p.student_name
   AND ps.cleaned_duration > 0
   AND ps.session_start >= p.period_start
   AND ps.session_start < wc.cutoff_at
   AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
),
recent20 AS (
  SELECT
    rr.student_name,
    COUNT(*)::INTEGER AS cnt,
    ROUND(AVG((rr.is_outlier)::INTEGER)::NUMERIC, 4) AS outlier_rate,
    ROUND(AVG(rr.cleaned_duration)::NUMERIC, 2) AS mean_dur
  FROM recent_ranked rr
  WHERE rr.rn <= 20
  GROUP BY rr.student_name
),
week_usage AS (
  SELECT
    p.student_name,
    COUNT(*)::INTEGER AS cnt
  FROM periods p
  CROSS JOIN week_context wc
  JOIN public.practice_sessions ps
    ON ps.student_name = p.student_name
   AND ps.cleaned_duration > 0
   AND ps.session_start >= GREATEST(wc.week_start, p.period_start)
   AND ps.session_start < wc.cutoff_at
   AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
  GROUP BY p.student_name
),
week_scores AS (
  SELECT
    ssh.student_name,
    ssh.composite_score,
    ssh.raw_score,
    ssh.trend_score,
    ssh.baseline_score
  FROM public.student_score_history ssh
  CROSS JOIN week_context wc
  JOIN week_usage wu ON wu.student_name = ssh.student_name
  WHERE ssh.snapshot_date = wc.monday
    AND ssh.composite_score > 0
),
last_week_scores AS (
  SELECT DISTINCT ON (ssh.student_name)
    ssh.student_name,
    ssh.composite_score AS previous_composite
  FROM public.student_score_history ssh
  JOIN periods p ON p.student_name = ssh.student_name
  CROSS JOIN week_context wc
  WHERE ssh.snapshot_date < wc.monday
    AND ssh.snapshot_date >= DATE_TRUNC(
      'week',
      p.period_start AT TIME ZONE 'Asia/Shanghai'
    )::DATE
    AND ssh.composite_score > 0
    AND EXISTS (
      SELECT 1
      FROM public.practice_sessions active_session
      WHERE active_session.student_name = ssh.student_name
        AND active_session.cleaned_duration > 0
        AND active_session.session_start >= GREATEST(
          p.period_start,
          (ssh.snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai'
        )
        AND active_session.session_start < (((ssh.snapshot_date + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
        AND EXTRACT(DOW FROM active_session.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
    )
  ORDER BY ssh.student_name, ssh.snapshot_date DESC
),
ranked_pool AS (
  SELECT
    p.student_name,
    p.student_major,
    p.student_grade,
    ws.composite_score AS display_score,
    p.alpha,
    ws.trend_score,
    p.mean_duration,
    p.record_count,
    wu.cnt AS week_sessions
  FROM periods p
  JOIN week_usage wu ON wu.student_name = p.student_name
  JOIN week_scores ws ON ws.student_name = p.student_name
  WHERE ws.composite_score > 0
),
comp AS (
  SELECT
    '综合榜'::TEXT AS board,
    RANK() OVER (
      ORDER BY rp.display_score DESC NULLS LAST,
               rp.mean_duration DESC NULLS LAST,
               rp.record_count DESC NULLS LAST
    )::INTEGER AS rank_no,
    rp.student_name,
    rp.student_major,
    rp.student_grade,
    rp.display_score,
    rp.alpha::NUMERIC,
    rp.trend_score,
    rp.mean_duration::NUMERIC,
    rp.record_count,
    r20.outlier_rate AS recent10_outlier_rate,
    r20.mean_dur AS recent10_mean_dur,
    r20.cnt AS recent10_count
  FROM ranked_pool rp
  LEFT JOIN recent20 r20 ON r20.student_name = rp.student_name
),
comp_top10 AS (
  SELECT c.student_name
  FROM comp c
  WHERE c.rank_no <= 10
),
progress AS (
  SELECT
    '进步榜'::TEXT AS board,
    RANK() OVER (
      ORDER BY (rp.display_score - lws.previous_composite) DESC NULLS LAST,
               rp.display_score DESC NULLS LAST,
               rp.mean_duration DESC NULLS LAST
    )::INTEGER AS rank_no,
    rp.student_name,
    rp.student_major,
    rp.student_grade,
    rp.display_score,
    rp.alpha::NUMERIC,
    ROUND((rp.display_score - lws.previous_composite)::NUMERIC, 1) AS trend_score,
    rp.mean_duration::NUMERIC,
    rp.record_count,
    r20.outlier_rate AS recent10_outlier_rate,
    r20.mean_dur AS recent10_mean_dur,
    r20.cnt AS recent10_count
  FROM ranked_pool rp
  JOIN last_week_scores lws ON lws.student_name = rp.student_name
  LEFT JOIN recent20 r20 ON r20.student_name = rp.student_name
  WHERE rp.display_score - lws.previous_composite >= 1.0
    AND rp.week_sessions >= 2
    AND COALESCE(r20.cnt, 0) >= 4
    AND COALESCE(r20.outlier_rate, 1) <= 0.20
    AND rp.student_name NOT IN (SELECT ct.student_name FROM comp_top10 ct)
),
stable AS (
  SELECT
    '稳定榜'::TEXT AS board,
    RANK() OVER (
      ORDER BY COALESCE(r20.mean_dur, 0) DESC NULLS LAST,
               rp.alpha DESC NULLS LAST,
               COALESCE(r20.outlier_rate, 1) ASC
    )::INTEGER AS rank_no,
    rp.student_name,
    rp.student_major,
    rp.student_grade,
    rp.display_score,
    rp.alpha::NUMERIC,
    rp.trend_score,
    rp.mean_duration::NUMERIC,
    rp.record_count,
    r20.outlier_rate AS recent10_outlier_rate,
    r20.mean_dur AS recent10_mean_dur,
    r20.cnt AS recent10_count
  FROM ranked_pool rp
  LEFT JOIN recent20 r20 ON r20.student_name = rp.student_name
  WHERE COALESCE(rp.alpha, 0) >= 0.60
    AND COALESCE(r20.cnt, 0) >= 8
    AND COALESCE(r20.outlier_rate, 1) <= 0.20
    AND COALESCE(r20.mean_dur, 0) >= 30
    AND rp.student_name NOT IN (SELECT ct.student_name FROM comp_top10 ct)
),
rules AS (
  SELECT
    '守则榜'::TEXT AS board,
    RANK() OVER (
      ORDER BY COALESCE(r20.outlier_rate, 1) ASC,
               rp.week_sessions DESC NULLS LAST,
               COALESCE(r20.mean_dur, 0) DESC
    )::INTEGER AS rank_no,
    rp.student_name,
    rp.student_major,
    rp.student_grade,
    rp.display_score,
    rp.alpha::NUMERIC,
    rp.trend_score,
    rp.mean_duration::NUMERIC,
    rp.record_count,
    r20.outlier_rate AS recent10_outlier_rate,
    r20.mean_dur AS recent10_mean_dur,
    r20.cnt AS recent10_count
  FROM ranked_pool rp
  LEFT JOIN recent20 r20 ON r20.student_name = rp.student_name
  WHERE rp.week_sessions >= 3
    AND COALESCE(r20.cnt, 0) >= 5
    AND COALESCE(r20.mean_dur, 0) >= 30
    AND COALESCE(r20.outlier_rate, 1) <= 0.20
    AND COALESCE(rp.alpha, 0) >= 0.60
    AND rp.student_name NOT IN (SELECT ct.student_name FROM comp_top10 ct)
)
SELECT * FROM comp
UNION ALL
SELECT * FROM progress
UNION ALL
SELECT * FROM stable
UNION ALL
SELECT * FROM rules
ORDER BY board, rank_no;
$function$;

REVOKE ALL ON FUNCTION public.get_weekly_leaderboards() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_weekly_leaderboards() TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.start_new_semester(p_confirm TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count         INTEGER;
  v_total_cleared INTEGER;
  v_started_at    TIMESTAMPTZ;
  v_week_monday   DATE;
  v_target_snapshot JSONB;
BEGIN
  IF p_confirm <> 'CONFIRM_NEW_SEMESTER' THEN
    RETURN '❌ 安全确认失败。请传入字符串 "CONFIRM_NEW_SEMESTER" 方可执行。';
  END IF;

  v_started_at := clock_timestamp();
  v_week_monday := DATE_TRUNC('week', v_started_at AT TIME ZONE 'Asia/Shanghai')::DATE;

  -- 先保存已有老生目标，再建立新学期边界；新生不写入快照，后续按同教研室
  -- 平均目标或默认 270 分钟冷启动。
  v_target_snapshot := public.capture_score_semester_targets(v_started_at);

  INSERT INTO public.score_semesters (started_at, source, week_target_snapshot)
  VALUES (
    v_started_at,
    'manual_semester_reset',
    v_target_snapshot
  )
  ON CONFLICT (started_at) DO NOTHING;

  INSERT INTO public.student_coins (student_name, balance, semester_earned)
  SELECT sd.name, 0, 0
  FROM public.student_database sd
  ON CONFLICT (student_name) DO NOTHING;

  INSERT INTO public.coin_transactions (
    student_name,
    amount,
    balance_after,
    reason,
    transaction_type
  )
  SELECT
    sc.student_name,
    -sc.balance,
    0,
    '开启新学期：清空音符币余额（原余额 ' || sc.balance || '，本学期累计 '
      || sc.semester_earned || '）。',
    'semester_reset'
  FROM public.student_coins sc
  ORDER BY sc.student_name;
  GET DIAGNOSTICS v_count = ROW_COUNT;

  SELECT COALESCE(SUM(GREATEST(sc.balance, 0)), 0)
  INTO v_total_cleared
  FROM public.student_coins sc;

  UPDATE public.student_coins
  SET
    balance = 0,
    semester_earned = 0,
    updated_at = NOW()
  WHERE student_name IS NOT NULL;

  PERFORM set_config('app.skip_score_trigger', 'on', true);
  PERFORM set_config('app.computing_score', 'true', true);

  UPDATE public.student_score_history h
  SET
    composite_score = 0,
    raw_score = 0.0,
    baseline_score = NULL,
    trend_score = NULL,
    momentum_score = NULL,
    accum_score = NULL,
    outlier_rate = 0.0,
    short_session_rate = 0.0,
    mean_duration = 0.0,
    record_count = 0
  WHERE h.snapshot_date = v_week_monday;

  UPDATE public.student_baseline sb
  SET
    composite_score = 0,
    raw_score = 0.0,
    baseline_score = NULL,
    trend_score = NULL,
    momentum_score = NULL,
    accum_score = NULL,
    w_score = 0.0,
    score_confidence = 0.0,
    growth_velocity = 0.0,
    weeks_improving = 0,
    last_updated = NOW()
  WHERE sb.student_name IS NOT NULL;

  PERFORM set_config('app.computing_score', 'false', true);
  PERFORM set_config('app.skip_score_trigger', 'off', true);

  RETURN '✅ 新学期已开启，共清空 ' || v_count || ' 位学生的音符币余额，合计清空 '
    || v_total_cleared || ' 枚；评分历史已从本学期边界重新起算。';
END;
$function$;

REVOKE ALL ON FUNCTION public.start_new_semester(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.start_new_semester(TEXT) TO anon, authenticated;

-- 清除“没有真实练琴却复制旧高分”的历史派生快照，不改练琴原始记录、
-- 音符币流水或已经归档的周榜事实。
UPDATE public.student_score_history history
SET
  composite_score = 0,
  raw_score = 0.0,
  baseline_score = NULL,
  trend_score = NULL,
  momentum_score = NULL,
  accum_score = NULL,
  outlier_rate = 0.0,
  short_session_rate = 0.0,
  mean_duration = 0.0,
  record_count = 0
WHERE NOT EXISTS (
  SELECT 1
  FROM public.practice_sessions ps
  WHERE ps.student_name = history.student_name
    AND ps.cleaned_duration > 0
    AND ps.session_start >= ((history.snapshot_date::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
    AND ps.session_start < (((history.snapshot_date + 7)::TIMESTAMP) AT TIME ZONE 'Asia/Shanghai')
    AND EXTRACT(DOW FROM ps.session_start AT TIME ZONE 'Asia/Shanghai') NOT IN (0, 6)
);

DO $block$
DECLARE
  student_row RECORD;
BEGIN
  PERFORM set_config('app.skip_score_trigger', 'on', true);

  FOR student_row IN
    SELECT sb.student_name
    FROM public.student_baseline sb
    ORDER BY sb.student_name
  LOOP
    BEGIN
      PERFORM public.compute_student_score(student_row.student_name);
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING '[score period refresh] % 刷新失败：%', student_row.student_name, SQLERRM;
    END;
  END LOOP;

  PERFORM set_config('app.skip_score_trigger', 'off', true);
END;
$block$;

NOTIFY pgrst, 'reload schema';

COMMIT;
